/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aaswiper: typeof import('./src/components/aaswiper.vue')['default']
    Aaswiper2: typeof import('./src/components/aaswiper2.vue')['default']
    Aaswiper3: typeof import('./src/components/aaswiper3.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
